#!/usr/bin/env bash
# Enable Korean text on the monitor console (tty1).
#   - kmscon: replace the default console with one that can render Korean
#   - Font: Noto Sans Mono CJK KR (fixed-width Latin text prevents overlap)
#   - Resolution: kernel boot option video=<connector>:<resolution>
#
# Usage: sudo bash setup-korean-console.sh
#         sudo RESOLUTION=1280x720 bash setup-korean-console.sh
# Target: Ubuntu 24.04 with GRUB; graphics drivers installed and rebooted
set -euo pipefail

# Keep system command output in English before Korean rendering is available.
export LC_ALL=C

FONT_NAME=${FONT_NAME:-Noto Sans Mono CJK KR}
FONT_SIZE=${FONT_SIZE:-20}
RESOLUTION=${RESOLUTION-1680x1050}   # An empty value (RESOLUTION=) skips resolution setup
CONNECTOR=${CONNECTOR:-}             # An empty value auto-detects the connected monitor

KMSCON_CONF=/etc/kmscon/kmscon.conf
GRUB_MAIN=/etc/default/grub
GRUB_DROPIN=/etc/default/grub.d/99-korean-console.cfg

die() {
  printf 'Error: %s\n' "$@" >&2
  exit 1
}

[[ $EUID -eq 0 ]] || die "Root privileges are required: sudo bash $0"
ts=$(date +%Y%m%d-%H%M%S)

# 1. Validate resolution support before making any changes.
if [[ -n $RESOLUTION ]]; then
  [[ $RESOLUTION =~ ^[0-9]+x[0-9]+$ ]] || die "RESOLUTION must use the format 1680x1050: $RESOLUTION"
  command -v update-grub >/dev/null ||
    die "update-grub was not found. If you do not use GRUB, set RESOLUTION= to skip resolution setup."

  if [[ -z $CONNECTOR ]]; then
    connected=()
    for status in /sys/class/drm/card*-*/status; do
      [[ -r $status ]] || continue
      if [[ $(<"$status") == connected ]]; then
        name=$(basename "$(dirname "$status")")
        connected+=("${name#card*-}")
      fi
    done
    if (( ${#connected[@]} == 0 )); then
      die "No connected monitor was found." \
          "Make sure the graphics drivers are installed, the system has been rebooted, and the monitor is connected." \
          "To specify a connector manually: sudo CONNECTOR=DP-4 bash $0"
    elif (( ${#connected[@]} > 1 )); then
      die "Multiple monitors are connected: ${connected[*]}" \
          "Specify a connector: sudo CONNECTOR=${connected[0]} bash $0"
    fi
    CONNECTOR=${connected[0]}
  fi

  connector_dirs=(/sys/class/drm/card*-"$CONNECTOR")
  [[ -e ${connector_dirs[0]} ]] || die "Monitor connector '$CONNECTOR' was not found."
  modes_file=${connector_dirs[0]}/modes
  if ! grep -qx "$RESOLUTION" "$modes_file"; then
    die "The monitor on $CONNECTOR does not support resolution $RESOLUTION." \
        "Supported resolutions: $(awk '!seen[$0]++' "$modes_file" | tr '\n' ' ')"
  fi
fi

echo "=== Settings"
echo "Font:       $FONT_NAME ($FONT_SIZE)"
if [[ -n $RESOLUTION ]]; then
  echo "Resolution: $CONNECTOR $RESOLUTION"
else
  echo "Resolution: skipped"
fi
echo

# 2. Install packages.
export DEBIAN_FRONTEND=noninteractive
apt-get update
if [[ -z $(apt-cache policy kmscon | awk '/Candidate:/ && $2 != "(none)" {print $2}') ]]; then
  die "The kmscon package was not found. Enable the universe repository and run this script again:" \
      "  sudo add-apt-repository universe"
fi
# Wait up to 10 minutes if automatic updates hold the dpkg lock.
# Use APT's lock wait option so package installation itself is not interrupted.
echo "Installing packages: if another update is running, wait up to 10 minutes for the lock to be released."
if ! apt-get -o DPkg::Lock::Timeout=600 install -y kmscon fonts-noto-cjk fontconfig; then
  die "Package installation failed. Check the apt errors above." \
      "If this is a package lock error, wait for automatic updates to finish, then run this script again:" \
      "  sudo bash $0"
fi

[[ -n $(fc-list "$FONT_NAME" family) ]] || die "Font '$FONT_NAME' was not found."

# 3. Configure kmscon (back up an existing file if its contents differ).
mkdir -p /etc/kmscon
new_conf=$(cat <<EOF
# Generated by setup-korean-console.sh
# Render Korean with Pango using a monospace font to prevent overlapping Latin text.
font-engine=pango
font-name=$FONT_NAME
font-size=$FONT_SIZE

# Render the display using DRM/KMS.
drm

term=xterm-256color
EOF
)
if [[ -f $KMSCON_CONF && $(<"$KMSCON_CONF") != "$new_conf" ]]; then
  cp -a "$KMSCON_CONF" "$KMSCON_CONF.bak-$ts"
fi
printf '%s\n' "$new_conf" > "$KMSCON_CONF"

# Validate the configuration first: kmscon exits if any option is unknown.
# Use a nonexistent seat to read the configuration without taking over the display.
check=$(timeout 10 kmscon -c /etc/kmscon --seats=seat-nonexistent --no-switchvt 2>&1 || true)
if grep -q 'cannot load configuration' <<<"$check"; then
  echo "$check" >&2
  die "kmscon could not load $KMSCON_CONF."
fi

# 4. Enable kmscon on tty1 at boot.
systemctl enable kmsconvt@.service

# 5. Set the resolution using a kernel boot option.
if [[ -n $RESOLUTION ]]; then
  # Remove video= for the same connector from the main file to avoid duplicate options.
  if grep -qE "^GRUB_CMDLINE_LINUX_DEFAULT=.*video=$CONNECTOR:" "$GRUB_MAIN"; then
    cp -a "$GRUB_MAIN" "$GRUB_MAIN.bak-$ts"
    sed -i -E "/^GRUB_CMDLINE_LINUX_DEFAULT=/{s/ *video=$CONNECTOR:[^ \"']*//g; s/=([\"']) +/=\1/}" "$GRUB_MAIN"
  fi

  mkdir -p "$(dirname "$GRUB_DROPIN")"
  cat > "$GRUB_DROPIN" <<EOF
# Generated by setup-korean-console.sh: monitor console resolution
GRUB_CMDLINE_LINUX_DEFAULT="\$GRUB_CMDLINE_LINUX_DEFAULT video=$CONNECTOR:$RESOLUTION"
EOF

  update-grub
  grep -q "video=$CONNECTOR:$RESOLUTION" /boot/grub/grub.cfg ||
    die "video=$CONNECTOR:$RESOLUTION was not applied to /boot/grub/grub.cfg."
fi

# 6. Check the system locale (Korean text requires UTF-8).
if ! grep -qiE '^LANG=.*utf-?8' /etc/default/locale 2>/dev/null; then
  echo
  echo "Warning: the system locale is not UTF-8. If Korean text is garbled, run:"
  echo "  sudo update-locale LANG=C.UTF-8"
fi

# Apply kmscon on reboot: this script may be running on the monitor console.
# Restarting kmscon now could disconnect the tty1 login session and terminate this script.
echo
echo "Done: reboot to apply the settings."
echo "  sudo reboot"
